# Generated by Django 4.2.23 on 2025-08-01 08:17

from django.db import migrations


def create_auth_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    default_groups = ["admin"]  # or multiple like in your working project
    for group_name in default_groups:
        Group.objects.get_or_create(name=group_name)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_auth_groups),
    ]
